### PR TITLE
Support Symfony 7

### PR DESCRIPTION
**Pull request by endroid**
Adds support for Symfony 7

### CODE REVIEW

**Comment by endroid** [comment]
Can someone please check this MR. Symfony 7 is about to be released and I'd like to know of any more effort than bumping the versions is necessary.

**Comment by alexpozzi** [comment]
Hello,
It would be good to add a test case to ensure everything works fine with Symfony 7.x

**Comment by endroid** [comment]
The test matrix is updated to reflect the new supported versions.

**Comment by alexpozzi** [comment]
Replaced by https://github.com/KnpLabs/snappy/pull/496

**Pull request closed without merging**
