### PR TITLE
fixed that passing an empty array as env argument would clean default environment variables within the forked process

### PR DESCRIPTION
**Pull request by craue**
Just a quick and dirty approach to fix an issue introduced with #131, see KnpLabs/KnpSnappyBundle#83. Let me know if there's a cleaner solution.

/cc @TheBeakerMan, @plakjeworst

### CODE REVIEW

**Comment by craue** [comment]
Could someone please give feedback or merge this soon?

**Comment by LaurentBrieu** [comment]
:+1:

**Pull request merged**
