### PR TITLE
Add support for cache-dir option

### PR DESCRIPTION
**Pull request by crellbar**
Simply adds support for the wkhtmltopdf cache-dir option to the pdf generator.

### CODE REVIEW

**Comment by akovalyov** [comment]
@crellbar nice. Is it available only since wkhtmltopdf 0.12?

**Comment by crellbar** [comment]
@akovalyov I'm not sure exactly when it was added but it certainly works with 0.12.2

**Comment by akovalyov** [comment]
Yes, just found - https://github.com/wkhtmltopdf/wkhtmltopdf/releases/tag/0.12.0
Well, I am +1 for that.
@docteurklein @jeremyb what do you think?

**Comment by pilot** [comment]
@crellbar add comment to the readme about that `cache-dir` option required >= 0.12 version of wk

**Comment by crellbar** [comment]
@pilot The comment has been added. Any chance of getting this merged in?

**Pull request merged**
