### PR TITLE
header-html and footer-html in all the generation methods

### PR DESCRIPTION
**Pull request by dstollie**
#33 added a handy handleOptions() method and overrided the generate() method to make use of the handleOptions(). But the methods generateFromHtml(), getOutput(), getOutputFromHtml() don't have this implementation.. a bit weird if you ask me

### CODE REVIEW

**Comment by supertanuki** [comment]
+1

**Comment by pilot** [comment]
good +1

**Comment by akovalyov** [comment]
@pilot wait - https://github.com/KnpLabs/snappy/pull/160#issue-85017916

**Comment by pilot** [comment]
@akovalyov just ask him rebase, there not to much

**Comment by akovalyov** [comment]
I just want to tell that that PR also fixes this issue but in different manner and these two solutions are inconsistent. 

So, in this case we should check which one is more applicable and either I will revert mine fix or this PR should be reverted.

**Pull request merged**
