### PR TITLE
allow Symfony 6

### PR DESCRIPTION
**Pull request by garak**

### CODE REVIEW

**Comment by garak** [comment]
Tests are failing, #445 needs to be merged before this PR

**Comment by garak** [comment]
The failing test is unrelated.
I can propose a fix in a separate PR

**Comment by garak** [comment]
> thanks @garak , any update on this ?

I'm not sure if "any news" question is directed to me... I can only hope this PR will be merged soon.

**Comment by alexpozzi** [comment]
Thank you! I'm gonna hopefully have some time soon to check the issue with the logger.

**Comment by jonbk** [comment]
Many thanks both of you :)

**Pull request merged**
